version: '3.7'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
      
  django:
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    env_file:
      - ./.env
    volumes:
      - .:/stocks_products/


  nginx:
    build: 
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./static/:/static
      # - ./media:/media
    depends_on:
      - django
    restart: always